// @desc Planning protocol slot — visible only in plan_mode, guides structured plan workflow
import type { SlotFactory } from "#src/capability/slot/types.js";
import { SlotPriority } from "#src/capability/slot/types.js";
import { TEAMBOARD_KEYS } from "#src/defaults/teamboard-vars.js";

const CONTENT = [
  "## Plan Mode Active",
  "",
  "You are in **plan_mode**. DO NOT start coding or making changes yet.",
  "Focus entirely on understanding the problem and designing an actionable plan.",
  "",
  "### Phase 1: Explore",
  "Gain a comprehensive understanding of the task and relevant code.",
  "",
  "- **Start with `docs/principles/`** — read all principle files to internalize project standards and constraints",
  "- Read files provided in the request; search for existing patterns and conventions",
  "- Trace through relevant code paths; identify similar features as reference",
  "- Actively search for functions, utilities, and patterns that can be reused",
  "- Use subagents for parallel exploration when the scope is uncertain or spans multiple areas",
  "- Use web search when the task involves unfamiliar APIs or external systems",
  "",
  "### Phase 2: Design",
  "Create a concrete implementation plan based on what you learned.",
  "",
  "- Identify the minimal set of changes needed",
  "- Consider trade-offs and pick an approach",
  "- Use `create_plan` to persist the plan with body text + todo list",
  "",
  "#### Plan format",
  "",
  "The `content` parameter is the plan body — write it as a self-contained analysis document.",
  "The `todos` parameter is the actionable task list derived from the body.",
  "",
  "Example:",
  "",
  "```",
  'create_plan({',
  '  name: "add-cache-layer",',
  '  content: `',
  "## Context",
  "",
  "TeamBoard 每轮 turn 读一次 teamboard.json，当前 5 个 agent 并发时",
  "每秒约 25 次磁盘读取。profiling 显示 readFileSync 占 turn 耗时的 12%。",
  "",
  "## Approach",
  "",
  "在 TeamBoard 内部加一层内存缓存 + FSWatcher 同步（符合 P1 的合理有状态场景三：",
  "同步路径封闭在 TeamBoard 单一组件内）。对外接口不变。",
  "",
  "## Key Decisions",
  "",
  "- 用 FSWatcher 而非轮询：变更通知实时且 CPU 开销可忽略",
  "- 自写屏蔽窗口 500ms：避免自己的 writeFile 触发自己的 reload",
  "- 不暴露缓存 API：外部调用方无感知，缓存失效逻辑完全内聚",
  "",
  "## Risks",
  "",
  "- FSWatcher 在某些文件系统（如 NFS）上不可靠 → 降级为定时轮询",
  "- 自写屏蔽窗口太短可能误触发 → 需要实测校准",
  '  `,',
  '  todos: [',
  '    { id: "t1", content: "在 team-board.ts 中添加 Map 缓存 + read-through 逻辑" },',
  '    { id: "t2", content: "注册 FSWatcher 监听 teamboard.json，变更时 reloadFromDisk" },',
  '    { id: "t3", content: "实现自写屏蔽：writeFile 后 500ms 内忽略 watcher 通知" },',
  '    { id: "t4", content: "验证：tsc + lint + 手动测试 5-agent 并发场景" },',
  '  ]',
  "})",
  "```",
  "",
  "### Phase 3: Review",
  "Assess the plan before execution.",
  "",
  "- Use `review_plan` to spawn a review subagent that evaluates the plan against project principles",
  "- If verdict is `revise`, update the plan with `create_plan`",
  "- If verdict is `ready`, call `execute_plan` to begin",
  "",
  "### Exit Options",
  "- `execute_plan` — sync todos and start coding (exits plan_mode)",
  "- `exit_plan_mode` — discard plan and return to normal operation without executing",
  "",
  "### When Uncertain — Ask, Don't Guess",
  "",
  "If you encounter any ambiguity, missing context, or unclear requirement during planning:",
  "",
  "- **With a user present**: Stop and ask directly in your response. Do not wrap it in a tool call.",
  "- **With a parent agent**: Use `dispatch_up` to ask your question.",
  "- **Never guess and continue.** An incorrect assumption baked into a plan causes more wasted work than a brief pause to clarify.",
  "",
  "### Quality Checklist (Self-Review After create_plan)",
  "",
  "After writing a plan, run this checklist before calling `review_plan`:",
  "",
  "1. **Placeholder scan**: Any \"TBD\", \"TODO\", \"fill in later\", or vague descriptions? Fix them — every step must be concrete.",
  "2. **Scope check**: Is this one coherent task, or should it be split into multiple plans? If the plan covers unrelated subsystems, decompose first.",
  "3. **Internal consistency**: Do later todos depend on assumptions made in earlier ones? Do todos match the approach described in the body?",
  "4. **Ambiguity check**: Could any todo be interpreted two different ways? Make it explicit.",
  "",
  "Fix issues inline. No need to re-create — use `edit_plan` for targeted fixes.",
  "",
  "### Rules",
  "- Only `create_plan`, `edit_plan`, `review_plan`, `execute_plan`, `exit_plan_mode`, and read-only tools are relevant now",
  "- Do NOT make file edits or run side-effecting commands in plan_mode",
  "- A plan is not static — re-evaluate when you learn new information",
].join("\n");

const create: SlotFactory = (ctx) => ({
  name: "planning-protocol",
  // Demoted to dynamic: condition-based on STATUS === "plan_mode". Toggling
  // plan_mode would inject/remove an entire stable block, busting the cache.
  // Living in the dynamic section means condition flips don't affect stable
  // prefix integrity.
  priority: SlotPriority.DYNAMIC_DEFAULT,
  cacheHint: "dynamic",
  content: CONTENT,
  version: 0,
  condition: (c) => c.teamBoard.get(c.agentId, TEAMBOARD_KEYS.STATUS) === "plan_mode",
});

export default create;
