/** @desc .include-pack generation and parsing for team↔pack sync */

import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { existsSync } from "node:fs";

const EXCLUDED_ENTRIES = new Set([".git", "pack.json", "image.tar", ".built"]);

const USER_SECTION_MARKER = "# ──── USER SECTION (手动追加的条目，updateTeam 时保留) ────";

const HEADER = `# Auto-generated by loadPack — pack source files (excluding .git and build artifacts)
# Entries below are synced between pack and team.
`;

const ALWAYS_EXCLUDED_COMMENT = `
# Always excluded (not synced in either direction):
# .git/           ← 只存在于 pack，不复制到 team，不回写
# pack.json       ← stripPackOnlyFiles 已移除，manifest.json 替代
# image.tar       ← build artifact
# .built          ← build marker
# manifest.json   ← team 运行时生成
# .include-pack   ← 本文件自身
`;

/** List top-level entries in a pack directory, excluding non-syncable files. */
export async function listPackEntries(packDir: string): Promise<string[]> {
  const entries = await readdir(packDir, { withFileTypes: true });
  const result: string[] = [];
  for (const e of entries) {
    if (EXCLUDED_ENTRIES.has(e.name)) continue;
    result.push(e.isDirectory() ? `${e.name}/` : e.name);
  }
  return result.sort();
}

/** Generate the full .include-pack content from a list of pack entries. */
export function generateIncludePack(entries: string[], userSection?: string): string {
  let content = HEADER;
  for (const e of entries) content += `${e}\n`;
  content += ALWAYS_EXCLUDED_COMMENT;
  content += `\n${USER_SECTION_MARKER}\n`;
  if (userSection) content += userSection;
  return content;
}

/** Parse .include-pack, return { autoEntries, userSection }. */
export function parseIncludePack(content: string): { autoEntries: string[]; userSection: string } {
  const markerIdx = content.indexOf(USER_SECTION_MARKER);
  const autoPart = markerIdx >= 0 ? content.substring(0, markerIdx) : content;
  const userSection = markerIdx >= 0 ? content.substring(markerIdx + USER_SECTION_MARKER.length + 1) : "";

  const autoEntries: string[] = [];
  for (const line of autoPart.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    autoEntries.push(trimmed);
  }

  return { autoEntries, userSection };
}

/** Read the user section from an existing .include-pack file (preserves manual additions). */
export async function readUserSection(teamRoot: string): Promise<string> {
  const filePath = join(teamRoot, ".include-pack");
  if (!existsSync(filePath)) return "";
  try {
    const content = await readFile(filePath, "utf-8");
    const { userSection } = parseIncludePack(content);
    return userSection;
  } catch {
    return "";
  }
}
